# deploy app to azure
trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool  # Specify the name of your agent pool

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: 'Build and Publish .NET App'
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.x'  # Change based on your .NET version

          - script: dotnet build --configuration Release
            displayName: 'Build the project'
            workingDirectory: 'MyFirstAzureWebApp'  # Adjust path to your app's subdirectory

          - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
            displayName: 'Publish the app'
            workingDirectory: 'MyFirstAzureWebApp'  # Adjust path to your app's subdirectory

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: 'drop'

  - stage: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        steps:
          - task: AzureWebApp@1
            inputs:
              #azureSubscription: '<Your Azure Service Connection>'
              #appName: '<Your Azure Web App Name>'
              #package: '$(Build.ArtifactStagingDirectory)'
              azureSubscription: 'AzureService'
              appType: 'webAppLinux'
              appName: 'webappffo'
              package: '$(Build.ArtifactStagingDirectory)'